FROM node:23

WORKDIR /app

# Копируем файлы зависимостей
COPY app/package.json app/package-lock.json ./

# Устанавливаем все зависимости
RUN npm install

# Копируем все файлы приложения
COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production

# Собираем приложение
RUN make build

CMD make start
