FROM node:20.12.2

WORKDIR /app

# Копируем package.json
COPY app/package.json ./

# Устанавливаем все зависимости без package-lock.json
RUN npm install --package-lock false

# Копируем package-lock.json из приложения (для информации)
COPY app/package-lock.json ./

COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production

RUN make build

CMD make start
