FROM node:20.12.2

WORKDIR /app

COPY app/package.json app/package-lock.json ./

RUN npm install --production

RUN npm install rolldown @rolldown/binding-linux-x64-gnu

COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make start
